server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include:
          '*'
        
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MicroServDB